/* This file is generated by scripts/build-ferry-data.mjs. Do not edit directly. */
export const ferryDataGenerated = {
  "projection": {
    "origin": [
      118.6982074,
      32.0354297
    ],
    "metersPerDegreeLongitude": 94456.78797114191,
    "metersPerDegreeLatitude": 110887.42962189173
  },
  "terminals": [
    {
      "id": "qigan-pier",
      "name": {
        "zh": "旗杆码头（旗杆渡口）",
        "en": "Qigan Ferry Terminal"
      },
      "coordinate": [
        118.6975913,
        32.009866
      ],
      "bank": "jiangxinzhou",
      "modelLod1": "/models/jiangxinzhou-v2/ferry-qigan-pier-lod1.glb",
      "modelLod2": "/models/jiangxinzhou-v2/ferry-qigan-pier-lod2.glb",
      "placement": {
        "waterAnchor": [
          118.6975913,
          32.009866
        ],
        "landEntranceAnchor": [
          118.697381,
          32.009977
        ],
        "headingDeg": -29,
        "berthOffsetM": [
          12.2,
          6.8
        ],
        "cameraBoundsM": [
          72,
          34,
          30
        ]
      },
      "confidence": "triangulated"
    },
    {
      "id": "mianhuadi-pier",
      "name": {
        "zh": "棉花堤渡口",
        "en": "Mianhuadi Ferry Pier"
      },
      "coordinate": [
        118.6999968,
        32.0087366
      ],
      "bank": "mainland-east-bank",
      "modelLod1": "/models/jiangxinzhou-v2/ferry-mianhuadi-pier-lod1.glb",
      "modelLod2": "/models/jiangxinzhou-v2/ferry-mianhuadi-pier-lod2.glb",
      "placement": {
        "waterAnchor": [
          118.6999968,
          32.0087366
        ],
        "landEntranceAnchor": [
          118.700228,
          32.008621
        ],
        "headingDeg": 151,
        "berthOffsetM": [
          -12.2,
          -6.8
        ],
        "cameraBoundsM": [
          78,
          38,
          32
        ]
      },
      "confidence": "triangulated"
    }
  ],
  "route": {
    "id": "ferry-qigan",
    "coordinates": [
      [
        118.6975913,
        32.009866
      ],
      [
        118.6987921,
        32.0093063
      ],
      [
        118.6999968,
        32.0087366
      ]
    ],
    "measuredGeometryLengthM": 260,
    "lengthStatus": "mapped",
    "geometryKind": "direct-water-connection",
    "sourceAgreement": "osm-route-and-public-poi",
    "confidence": "triangulated",
    "osmWayId": 137693220,
    "note": "The mapped water connection follows OpenStreetMap way 137693220 and measures about 260m. The cited government and tourism sources do not publish an official ferry-route length."
  },
  "schedule": {
    "version": "12.0.0",
    "lineId": "ferry-qigan",
    "timezone": "Asia/Shanghai",
    "publishedWindow": {
      "start": "07:00",
      "end": "18:00"
    },
    "serviceBoundary": {
      "firstDeparture": "07:00",
      "lastMianhuadiDeparture": "18:00",
      "finalReturnDeparture": "18:10",
      "serviceEnd": "18:15"
    },
    "crossingDurationMin": 5,
    "departures": {
      "mianhuadi": [
        "07:00",
        "07:30",
        "08:00",
        "08:30",
        "09:00",
        "12:00",
        "17:00",
        "17:30",
        "18:00"
      ],
      "qigan": [
        "07:10",
        "07:40",
        "08:10",
        "08:40",
        "09:10",
        "12:10",
        "17:10",
        "17:40",
        "18:10"
      ]
    },
    "sourceStatus": "published",
    "verificationStatus": "secondary-published-reference",
    "displayPolicy": "Published schedule is a reference snapshot; same-day notices override it. When no same-day notice is available, show simulated / refer to same-day notices.",
    "sources": [
      "ferry-official-2024",
      "ferry-schedule-secondary-2026"
    ],
    "exceptions": {
      "weather": "suspended",
      "waterLevel": "suspended",
      "manualNotice": "suspended"
    }
  }
} as const;
