import type { Landmark } from "./landmarks";
import type { Language } from "./locales";
import type { CameraCommand, CameraPhase, LayerVisibility, RoadSublayerVisibility, SceneFocus, SceneQuality } from "./interactionState";
import type { RenderContextState, RenderMode, RenderProfile, RenderTelemetry } from "./render/runtime";
import type { GameMode, PlayerState } from "./game/types";
import type { TransitRealtimeSnapshot } from "./transit/realtime";

export type { LayerKey, LayerVisibility, SceneQuality, ViewMode } from "./interactionState";

export type ViewportInsets = { top: number; right: number; bottom: number; left: number };

export type JiangxinzhouSceneProps = {
  items: Landmark[];
  selectedId: number;
  onSelect: (id: number) => void;
  onReady: () => void;
  onScaleChange: (meters: number) => void;
  celestialTimestamp: number;
  routeId: string;
  focus: SceneFocus;
  cameraCommand: CameraCommand;
  cameraPhase: CameraPhase;
  reducedMotion: boolean;
  viewportInsets: ViewportInsets;
  onCameraPhaseChange: (phase: CameraPhase) => void;
  onSceneInteractionStart: () => void;
  onDetailedAssetStateChange: (state: "idle" | "loading" | "ready") => void;
  layers: LayerVisibility;
  roadSublayers: RoadSublayerVisibility;
  selectedRoadId?: string;
  onSelectRoad?: (roadId: string) => void;
  language: Language;
  quality: SceneQuality;
  renderMode: RenderMode;
  renderProfile: RenderProfile;
  renderContextState: RenderContextState;
  renderContextLosses: number;
  onPerformanceSample: (fps: number) => void;
  onRenderTelemetry: (telemetry: RenderTelemetry) => void;
  onRenderContextStateChange: (state: RenderContextState) => void;
  objectiveId?: number;
  expeditionLandmarkIds: readonly number[];
  discoveredLandmarkIds: readonly number[];
  selectedTransportLineId: string;
  selectedTransportStopId?: string;
  transitSnapshot?: TransitRealtimeSnapshot;
  onSelectTransportStop: (id: string) => void;
  selectedCrossingId: string;
  onSelectCrossing: (id: string) => void;
  gameMode?: GameMode;
  gamePlayers?: readonly PlayerState[];
  localPlayerId?: string;
  selectedPlayerId?: string;
  onSelectPlayer?: (playerId: string) => void;
};
